name: si_hicoach_fe
description: HiCoach FrontEnd w/Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.10.0
  intl: ^0.17.0
  provider: ^6.0.4
  http: ^0.13.5
  card_swiper: ^2.0.4
  collection:
  multiple_result: ^1.0.4
  dio: ^4.0.6
  get: ^4.6.5
  shared_preferences: ^2.0.15
  json_annotation: ^4.7.0
  file_picker: ^5.2.2
  flutter_sms: ^2.3.3
  logger: ^1.1.0
  http_parser: ^4.0.2
  mime: ^1.0.2
  photo_view: ^0.14.0
  iamport_flutter: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
